services:
  postgres-db:
    image: postgres:17.5
    container_name: local-postgres-compose
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: weather_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USER} -d ${DB_NAME}']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - backend

  gather-weather-backend:
    image: 5aradise/gather-weather-backend:latest
    container_name: com-backend
    restart: always
    ports:
      - '8080:8080'
    environment:
      ENV: dev

      SERVER_PORT: 8080

      DB_HOST: postgres-db
      DB_PORT: 5432
      DB_USER: myuser
      DB_PASSWORD: mypassword
      DB_NAME: weather_db

      MAIL_HOST: smtp.gmail.com
      MAIL_PORT: 587
      MAIL_SENDER: paradjzer@gmail.com
      MAIL_PASSWORD: bgiq vbvm swba rlfo

      WEATHERAPI_KEY: 028373183a7443b39c1170026251805
    depends_on:
      postgres-db:
        condition: service_healthy
    networks:
      - backend

  prometheus:
    image: prom/prometheus:latest
    container_name: local-prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - '9090:9090'
    networks:
      - backend

  grafana:
    image: grafana/grafana:latest
    container_name: local-grafana
    ports:
      - '3000:3000'
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
